---
global:
  auth:
    postgresPassword: "root"
    username: "niko"
    password: "niko"
    database: "niko"
image:
  tag: 10.21.0


primary:
  resources:
    limits:
      cpu: 250m
      memory: 500Mi

  persistence:
    enabled: true

  podSecurityContext:
    enabled: false

  containerSecurityContext:
    enabled: false
